options:
  # FIX for "invalid argument" error: Logs are sent only to Cloud Logging, 
  # bypassing the default GCS log bucket permission check.
  logging: CLOUD_LOGGING_ONLY

steps:
# Step 1: Build the image using Buildpacks and deploy directly to Cloud Run
# The --source=. flag triggers the Buildpack process automatically.
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - run
    - deploy
    - happyshop  # <-- REPLACE with your Cloud Run Service Name if different
    - --source=.
    - --region=asia-east1 # <-- REPLACE with your actual region (e.g., us-central1)
    - --service-account=happyshop-deployer@happyshop-475709.iam.gserviceaccount.com # <-- REPLACE with your full runtime Service Account Email
    - --no-allow-unauthenticated # <-- Change to --allow-unauthenticated if you want public access