options:
  # This setting tells Cloud Build to only use Cloud Logging for logs, 
  # bypassing the default Google Cloud Storage (GCS) log bucket, which 
  # solves the permission conflict with your custom service account.
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Use the official buildpack image to build the container
  - name: 'gcr.io/cloud-builders/buildpack'
    args:
      - build
      - --builder=gcr.io/buildpacks/builder:v1
      - --image=us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/happyshop:$COMMIT_SHA
      - . # Source directory is the current directory

  # Step 2: Deploy the image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - happyshop
      - --image=us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/happyshop:$COMMIT_SHA
      - --region=asia-east1
      - --no-allow-unauthenticated